import { PrismaClient } from "../../src/generated/prisma";

const survivorOfferings = [
  { name: "Bloody Party Streamers", image: null },
  { name: "Hollow Shell", image: null },
  { name: "Sealed Envelope", image: null },
  { name: "Bound Envelope", image: null },
  { name: "Coconut Scream Pie", image: null },
  { name: "Frightful Flan", image: null },
  { name: "Ghastly Gateau", image: null },
  { name: "Gruesome Gateau", image: null },
  { name: "Sacrificial Cake", image: null },
  { name: "Screech Cobbler", image: null },
  { name: "Terrormisu", image: null },
  { name: "Primrose Blossom Sachet", image: null },
  { name: "Fresh Primrose Blossom ", image: null },
  { name: "Fragrant Primrose Blossom ", image: null },
  { name: "Sweet William Sachet", image: null },
  { name: "Fresh Sweet William", image: null },
  { name: "Fragrant Sweet William", image: null },
  { name: "Bog Laurel Sachet", image: null },
  { name: "Fresh Bog Laurel", image: null },
  { name: "Fragrant Bog Laurel", image: null },
  { name: "Crispleaf Amaranth Sachet", image: null },
  { name: "Fresh Crispleaf Amaranth", image: null },
  { name: "Fragrant Crispleaf Amaranth", image: null },
  { name: "Chalk Pouch", image: null },
  { name: "Cream Chalk Pouch", image: null },
  { name: "Ivory Chalk Pouch", image: null },
  { name: "Salt Pouch", image: null },
  { name: "Black Salt Statuette", image: null },
  { name: "Vigo's Jar Salty Lips", image: null },
  { name: "Bloodied Blueprint", image: null },
  { name: "Torn Blueprint", image: null },
  { name: "Scratched Coin", image: null },
  { name: "Tarnished Coin", image: null },
  { name: "Cut Coin", image: null },
  { name: "Shiny Coin", image: null },
  { name: "Clear Reagent", image: null },
  { name: "Faint Reagent", image: null },
  { name: "Hazy Reagent", image: null },
  { name: "Murky Reagent", image: null },
  { name: "Annotated Blueprint", image: null },
  { name: "Vigo's Blueprint", image: null },
  { name: "Mouldy Oak", image: null },
  { name: "Rotten Oak", image: null },
  { name: "Petrified Oak", image: null },
  { name: "Putrid Oak", image: null },
  { name: "Azarov's Key", image: null },
  { name: "Grandma's Cookbook", image: null },
  { name: "Heart Locket", image: null },
  { name: "Charred Wedding Photograph", image: null },
  { name: "Beef Tallow Mixture", image: null },
  { name: "Airlock Doors", image: null },
  { name: "Alien Flora", image: null },
  { name: "Crow's eye", image: null },
  { name: "Jigsaw Piece", image: null },
  { name: "Shattered Bottle", image: null },
  { name: "Strode Realty Key", image: null },
  { name: "Hawkins National Laboratory ID", image: null },
  { name: "Shattered Glasses", image: null },
  { name: "MacMillan's Phalanx Bone", image: null },
  { name: "Damaged Photo", image: null },
  { name: "RPD Badge", image: null },
  { name: "The Last Mask", image: null },
  { name: "Mary's Letter", image: null },
  { name: "The Pied Piper", image: null },
  { name: "Ichorous Loam", image: null },
  { name: "Yamaoka Family Crest", image: null },
  { name: "Sacrificial Ward", image: null },
  { name: "Black Ward", image: null },
  { name: "White Ward", image: null },
  { name: "Shroud of Union", image: null },
  { name: "Shroud of Vanishing", image: null },
  { name: "Vigo's Shroud", image: null },
  { name: "Shroud of Separation", image: null },
];

export async function seedSurvivorOfferings(prisma: PrismaClient) {
  for (const offering of survivorOfferings) {
    await prisma.survivorOffering.upsert({
      where: { name: offering.name },
      update: { name: offering.name, image: null },
      create: { name: offering.name, image: null },
    });
    console.log(`✅ Added offering: ${offering.name}`);
  }
}
