import { PrismaClient } from "@/generated/prisma";

const killerPerks = [
  "A Nurse's Calling",
  "Agitation",
  "Alien Instinct",
  "All-Shaking Thunder",
  "Awakened Awareness",
  "Bamboozle",
  "Barbecue & Chilli",
  "Batteries Included",
  "Beast of Prey",
  "Blood Echo",
  "Bitter Murmur",
  "Blood Warden",
  "Bloodhound",
  "Brutal Strength",
  "Call of Brine",
  "Coulrophobia",
  "Cruel Limits",
  "Corrupt Intervention",
  "Coup de Grâce",
  "Dark Arrogance",
  "Dark Devotion",
  "Darkness Revealed",
  "Dead Man's Switch",
  "Deadlock",
  "Deathbound",
  "Deerstalker",
  "Discordance",
  "Dissolution",
  "Distressing",
  "Dominance",
  "Dragon's Grip",
  "Dying Light",
  "Enduring",
  "Eruption",
  "Fire Up",
  "Forced Hesitation",
  "Forced Penance",
  "Forever Entwined",
  "Franklin's Demise",
  "Friends 'till The End",
  "Furtive Chase",
  "Game Afoot",
  "Gearhead",
  "Genetics Limits",
  "Grim Embrace",
  "Haywire",
  "Help Wanted",
  "Hex: Blood Favor",
  "Hex: Crowd Control",
  "Hex: Devour Hope",
  "Hex: Face the Darkness",
  "Hex: Fortune's Fool",
  "Hex: Haunted Ground",
  "Hex: Huntress Lullaby",
  "Hex: No One Escapes Death",
  "Hex: Nothing But Misery",
  "Hex: Pentimento",
  "Hex: Plaything",
  "Hex: Retribution",
  "Hex: Ruin",
  "Hex: The Third Seal",
  "Hex: Thrill of the Hunt",
  "Hex: Two Can Play",
  "Hex: Undying",
  "Hoarder",
  "Hubris",
  "Human Greed",
  "Hysteria",
  "I'm All Ears",
  "Infectious Fright",
  "Insidious",
  "Iron Grasp",
  "Iron Maiden",
  "Knock Out",
  "Languid Touch",
  "Lethal Pursuer",
  "Leverage",
  "Lightborn",
  "Machine Learning",
  "Mad Grit",
  "Make Your Choice",
  "Mindbreaker",
  "Monitor & Abuse",
  "Nemesis",
  "No QUarter",
  "No Way Out",
  "None Are Free",
  "Nowhere to Hide",
  "Oppression",
  "Overcharge",
  "Overwhelming Presence",
  "Phantom Fear",
  "Play with Your Food",
  "Pop Goes the Weasel",
  "Predator",
  "Rancor",
  "Rapid Brutality",
  "Remember Me",
  "Save the Best for Last",
  "Scourge Hook: Floods of Rage",
  "Scourge Hook: Gift of Pain",
  "Scourge Hook: Hangman's Trick",
  "Scourge Hook: Jagged Compass",
  "Scourge Hook: Monstrous Shrine",
  "Scourge Hook: Pain Resonance",
  "Septic Touch",
  "Shadowborn",
  "Shattered Hope",
  "Sloppy Butcher",
  "Spies from the Shadows",
  "Spirit Fury",
  "Starstruck",
  "Stridor",
  "Superior Anatomy",
  "Surge",
  "Surveillance",
  "THWACK!",
  "Terminus",
  "Territorial Imperative",
  "Thanatophobia",
  "Thrilling Tremors",
  "Tinkerer",
  "Trail of Torment",
  "Unbound",
  "Undone",
  "Unforeseen",
  "Unnerving Presence",
  "Unrelenting",
  "Weave Attunement",
  "Whispers",
  "Zanshin Tactics",
].sort();

export async function seedKillerPerks(prisma: PrismaClient) {
  for (const name of killerPerks) {
    await prisma.killerPerk.upsert({
      where: { name },
      update: { name, image: null },
      create: { name, image: null },
    });
    console.log(`✅ Added: ${name}`);
  }
}
