name: Deploy to Vercel

on:
  push:
    branches:
      - main # ou master selon ton repo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout du repo
      - uses: actions/checkout@v3

      # 2. Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # adapte si tu utilises une autre version

      # 3. Installer pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # 4. Installer les dépendances
      - name: Install dependencies
        run: pnpm install

      # 5. Déployer la base de données
      - name: Run Prisma Migrations & Seed
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          pnpm run db:migrate:deploy
          pnpm run db:seed

      # 6. Build du projet
      - name: Build Project
        run: pnpm run build:no-lint

      # 7. Déployer sur Vercel
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          npx vercel --prod --token $VERCEL_TOKEN --confirm
